#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const packageJsonPath = join(__dirname, '../package.json')
const versionFilePath = join(__dirname, '../package-version.js')

const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'))
const version = packageJson.version || 'unknown'

const content = `// This file is auto-generated by .auto/prebuild.js
// DO NOT EDIT MANUALLY
export const VERSION = '${version}'
`

writeFileSync(versionFilePath, content, 'utf-8')
console.log(`✓ Generated package-version.js with version: ${version}`)
